replicaCount: 3
applicationName: "Pomelo"

image: 
  repository: iarevalo720/bootcampclt-api
  tag: "1.1"
  pullPolicy: IfNotPresent
  
app: 
  containerPort: 8080
  env: 
    aspnetcoreEnvironment: Development
  
service: 
  type: NodePort
  port: 80
  targetPort: 8080
    
postgres: 
  host: postgres-svc
  port: 5432
  database: cltdb
  username: cltuser
  password: "a.123456" # Para demo local. En equipos reales, no commitear.